### ISSUE TITLE
ADD profile button in home page and home page

### ISSUE THREAD

**Issue by akshitdesai** [codestromer/ContestReminder#11]
On the profile page, the users can change their preferences also give the option to delete their account (If they are no more interested in receiving reminder mail.)

**Comment by matt-ross16** [comment]
Jumping on this now!

**Comment by matt-ross16** [comment]
So this is what I have set up so far for the Profile page:

![image](https://user-images.githubusercontent.com/37879416/101988899-ac4f2500-3c6a-11eb-9294-7c711b7c6fc4.png)

However, I'm having issues with determining who the current user is within the "session". I've tried to look up all sorts of things that may solve the issue, but I haven't had the "eureka" moment yet. It looks like I should be able to access `request.sessions` right out of the gate based on doc I've read (https://docs.djangoproject.com/en/3.1/topics/http/sessions/#enabling-sessions), but it isn't recognizing my inputs.

This is the users/views.py file:
![image](https://user-images.githubusercontent.com/37879416/101988968-27184000-3c6b-11eb-951d-368d04f94f9d.png)

One thing to note: I know that the class `ProfileView` should be a `UpdateView` type rather than `CreateView`, but I set it this way to allow myself to see how the `Profile` page was looking.

Do you have any experience in authorization with Django?

**Comment by omij18** [comment]
i understand your question. i have done this update profile before, so here is how i did 

i had customUser model to update a view we have to make a form of UpdateView class.
you don't need to anything with session for this.

i have given sample code using this you will be able to do profileUpdate view 

```
class anyUpdateView(UpdateView):
    # all fields names that you wabt to update
    fields = ['field1', 'field2']
    # template for updateview 
    template_name = 'anyUpdateView.html'
    # success_url 
    success_url = reverse_lazy('url_name')

    # get object for which you want to update data from request eg., user
    def get_object(self):
        return self.request.user
```

for accessing user in template you can just use user.is_authenticated for authorization and based on that you can render conditional view like if not authenticated show login/signup button else it will be details of fields that you want to update.

ask any questions if you don't understand it.

refer this for more details - 
https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-editing/#updateview
more on class based views -
https://ccbv.co.uk/projects/Django/3.0/django.views.generic.edit/UpdateView/

**Comment by akshitdesai** [comment]
Thanks @ozx1812. 
Also,
if user is not logged In then you can use login required and redirect user to login route like this...

path('profile/', login_required(ProfileView.as_view(),login_url='/users/login') , name='profile')

**Comment by matt-ross16** [comment]
Thanks for the tips @codestromer @ozx1812 !

I have the Profile page functional now, and am trying to work out the kinks of the account deletion section.
I thought that I had all of the proper set-up done, but there's no output the the button is clicked.

I've pushed what I have so far: https://github.com/matt-ross16/ContestReminder/tree/issue-11
